### ISSUE TITLE
v0.5 Todo List

### ISSUE THREAD

**Issue by joshuadavidnelson** [joshuadavidnelson/disable-blog#8]
Items to be in future versions, these updates are being developed in the `0.5.0` branch.
- [x] Disable REST API for posts.
- [X] Disable XML-RPC for posts.
- [x] Hide blog-related settings in customizer view.
- [x] Hide post column in User table view.
- [X] Hide Posts, Categories, and Tags in Appearance > Menus ([Support Forum Issue](https://wordpress.org/support/topic/remove-blog-features-from-custom-menu-screens/))
- [X] Hide Posts, Categories, and Tags in Customizer > Menus.
- [X] Remove 'posts' from front-end query.
- [ ] Filter or remove post-related topics in help tabs.
- [ ] Remove posts from comment feeds, if comments are enabled.
- [ ] Remove posts from Media Library "uploaded to" column.
- [ ] Change count in category and tag screen, if taxonomies are supported by another post type.

**Comment by chesio** [comment]
Hi @joshuadavidnelson,

I have implemented the "_Hide Posts, Categories, and Tags in Appearance > Menus_" item on one of my websites, I'd be happy to make a PR. Should I make it against the 0.5.0 or the develop branch?

Cheers,
Česlav

**Comment by joshuadavidnelson** [comment]
Closing this issue, as we've addressed most of these items in #37 and/or moved to #39
